# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4PU5As3XxwSH1OHGwDX7l51teAcUwNi

Setup Python Environment
"""

pip install pandas

"""Load the Data"""

import pandas as pd

df = pd.read_csv('sales_data.csv')

# Show first rows
print(df.head())

"""Understanding Data"""

print(df.info())
print(df.describe())

"""Find Highest Profitable Product"""

top_product = df.groupby('Product')['Profit'].sum().idxmax()
top_profit = df.groupby('Product')['Profit'].sum().max()

print("Top Product:", top_product)
print("Total Profit:", top_profit)

"""Create Pivot Table"""

pivot_table = pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Category',
    aggfunc='sum'
)

print(pivot_table)

"""Create "Status" Column"""

def check_status(profit):
    if profit > 5000:
        return "High Margin"
    elif profit < 0:
        return "Review Required"
    else:
        return "Normal"

df['Status'] = df['Profit'].apply(check_status)

print(df)

"""Save Final Output"""

df.to_csv('final_sales_report.csv', index=False)
pivot_table.to_csv('pivot_report.csv')

import matplotlib.pyplot as plt

df.groupby('Region')['Sales'].sum().plot(kind='bar')
plt.title("Sales by Region")
plt.show()

print("\n=== EXECUTIVE SUMMARY ===")
print("Top Product:", top_product)
print("\nPivot Table:\n", pivot_table)

